### ISSUE TITLE
mvn build fails due to test failures

### ISSUE THREAD

**Issue by denisbetsi** [KPTechnologyLab/spring-data-crate#2]
Downloaded the repo, attempted to mvn clean install  

It fails, looking at the first error

12:27:15.325 [main] WARN  o.s.c.s.GenericApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cratePersistentEntitySchemaManager' defined in class org.springframework.data.crate.repository.support.SimpleCrateRepositoryIntegrationTest$CrateContextConfig: Invocation of init method failed; nested exception is org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []

I didn't see any information in the readme about having elasticsearch running. Or building this on a machine where create is installed. Is that the case to make build work?

**Comment by denisbetsi** [comment]
Also tried building this on a machine with latest build of Crate.io and it's failing another test

16:57:54.765 [main] DEBUG o.s.t.c.s.DirtiesContextTestExecutionListener - After test method: context [DefaultTestContext@a53bb6f testClass = SimpleCrateRepositoryIntegrationTest, testInstance = org.springframework.data.crate.repository.support.SimpleCrateRepositoryIntegrationTest@5e63cad, testMethod = shouldDelete@SimpleCrateRepositoryIntegrationTest, testException = org.springframework.dao.DataAccessResourceFailureException: [person][1] null; nested exception is SQLActionException{errorCode=5000, status=INTERNAL_SERVER_ERROR, stackTrace='org.elasticsearch.action.NoShardAvailableActionException: [person][1] null

**Comment by denisbetsi** [comment]
Looking at the log of crate.log

I see
[2016-03-01 16:57:55,197][DEBUG][action.admin.indices.delete] [ip-10-0-0-11] [person] failed to delete indices
org.elasticsearch.indices.IndexMissingException: [person] missing
    at org.elasticsearch.cluster.metadata.MetaDataDeleteIndexService$2.execute(MetaDataDeleteIndexService.java:157)
    at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:204)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:167)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by denisbetsi** [comment]
```
            Thread.sleep(500);
            repository.refreshTable();
            repository.delete(hasnain);
```

Adding sleep + refresh table cures the issue.

Although complexid tests fail and above is a hack of a larger issue of creating/deleting indexes in rapid succession causes some unpredictable results.

**Comment by hasnainjaved** [comment]
Hi,

The project has integration tests so you will need to have an instance if crate running locally.

Kindly have a look at the following issue as your exceptions are related to it

[https://github.com/crate/crate/issues/1453](url)

As the issue suggested, we added the following configuration in our test calss

`@Table(...., numberOfReplicas="0")`

Do keep this is mind that the project was developed with an old version of Crate. The behaviour might have changed in newer versions of Crate.

If you are still having issues, create an issue in Crate's git hub repository

Kind Regards.

**Comment by denisbetsi** [comment]
Great thank you, also the byComplexId  tests are failing as well. It's unable to cast from provided ID into String.

**Comment by hasnainjaved** [comment]
Hi,

I updated the crate client to the latest version 0.54.6 and ran the tests against it. The problem is with Crate DB. I have opened an issue with them

[https://github.com/crate/crate/issues/3320](url)

You can see from the staktrace that no spring data crate package is listed :)

Kind Regards

**Comment by denisbetsi** [comment]
You the man!
