### ISSUE TITLE
Is this project alive at all?

### ISSUE THREAD

**Issue by uded** [KPTechnologyLab/spring-data-crate#9]
Serious question, honestly!

**Comment by hasnainjaved** [comment]
Hi,

We created [jira issue](https://jira.spring.io/browse/DATACMNS-675) for this project and tried to bring it under the official spring data repositories but they have marked it as "not likely". If there is demand and adoption of Cratedb, then they will consider this project. 

Kind Regards

**Comment by uded** [comment]
Well, if you do not actively promote your DB and do not provide up-to-date spring data module... not likely anyone will use it. There I can agree with Spring team. But it's up to you to make it successful and make them accept your product and community implementation. Not up to them...

**Comment by hasnainjaved** [comment]
Just to be clear... It's not our DB :)

**Comment by uded** [comment]
Damn, just noticed that - it's not an official repo. Wow, OK, I have more and more doubts about Crate with every day... Thanks, sorry for bothering you!
